DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT (
PRO_ID      TEXT PRIMARY KEY,
PRO_NAME    TEXT NOT NULL,
PRO_PRICE   INTEGER NOT NULL,
PRO_COM     TEXT NOT NULL
);
INSERT INTO PRODUCT (PRO_ID, PRO_NAME, PRO_PRICE, PRO_COM) VALUES
('101', 'MOTHER BOARD',      3200, 'TECHPRO'),
('102', 'KEY BOARD',          450, 'KEYMAX'),
('103', 'ZIP DRIVE',          250, 'DATAFIX'),
('104', 'SPEAKER',            550, 'SOUNDCO'),
('105', 'MONITOR',           5000, 'VIEWTECH'),
('106', 'DVD DRIVE',          900, 'DATAFIX'),
('107', 'CD DRIVE',           800, 'DATAFIX'),
('108', 'PRINTER',           2600, 'PRINTPLUS'),
('109', 'REFILL CARTRIDGE',   350, 'PRINTPLUS'),
('110', 'MOUSE',              250, 'KEYMAX');
SELECT * FROM PRODUCT;
SELECT *
FROM PRODUCT
WHERE PRO_PRICE < 1000 AND PRO_COM = 'DATAFIX';
SELECT *
FROM PRODUCT
WHERE PRO_COM = 'KEYMAX' OR PRO_PRICE > 3000;
SELECT *
FROM PRODUCT
WHERE PRO_PRICE < 1000
AND (PRO_COM = 'DATAFIX' OR PRO_COM = 'KEYMAX');
SELECT *
FROM PRODUCT
WHERE PRO_NAME LIKE 'M%';
SELECT *
FROM PRODUCT
WHERE PRO_NAME LIKE '%DRIVE';
SELECT *
FROM PRODUCT
WHERE PRO_NAME LIKE '%PRINT%';
SELECT PRO_NAME, PRO_PRICE
FROM PRODUCT
WHERE PRO_PRICE = (
SELECT MIN(PRO_PRICE)
FROM PRODUCT
);
SELECT PRO_NAME, PRO_PRICE
FROM PRODUCT
WHERE PRO_PRICE = (
SELECT MAX(PRO_PRICE)
FROM PRODUCT
);
UPDATE PRODUCT
SET PRO_PRICE = 600
WHERE PRO_ID = '104';
SELECT *
FROM PRODUCT
WHERE PRO_ID = '104';
DELETE FROM PRODUCT
WHERE PRO_ID = '103';
SELECT * FROM PRODUCT;