CREATE TABLE IF NOT EXISTS STUDENTCLASS24 (
ROLL_NO TEXT PRIMARY KEY,
NAME TEXT NOT NULL,
ADDRESS TEXT,
PHONE TEXT,
AGE INTEGER
);
INSERT INTO STUDENTCLASS24 (ROLL_NO,NAME,ADDRESS,PHONE,AGE) VALUES
('1','RONALDO','LISBON','*********',41),
('2','MESSI','MIAMI','********',39),
('3','NEYMAR','BRASILIA','******',37),
('4','MBAPPE','PARIS','********',29),
('5','HALLAND','OSLO','*****',27),
('6','YAMAL','BARCELONA','******',19);

SELECT * FROM STUDENTCLASS24;

SELECT * FROM STUDENTCLASS24 WHERE AGE = 41 AND ADDRESS = 'LISBON';

SELECT * FROM STUDENTCLASS24 WHERE AGE = 39 AND NAME = 'MESSI';

SELECT * FROM STUDENTCLASS24 WHERE NAME = 'NEYMAR' OR NAME = 'MBAPPE';

SELECT * FROM STUDENTCLASS24 WHERE NAME = 'HALLAND' OR AGE = 27;

SELECT * FROM STUDENTCLASS24 WHERE AGE = 19 AND (NAME = 'YAMAL' OR NAME = 'NEYMAR');